version: '3'
services:
  frontend:
    build:
      context: .
    container_name: frontend
    image: ghcr.io/floatingpoints/sport-matcher:main
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
